export const HANDLE_CHANGE_SEARCH_FIELD = "HANDLE_CHANGE_SEARCH_FIELD";
export const HANDLE_CHANGE_CATEGORY = "HANDLE_CHANGE_CATEGORY";

export const FETCH_PRODUCTS_REQUEST="FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE="FETCH_PRODUCTS_FAILURE";
export const HANDLE_FOLLOW="HANDLE_FOLLOW";


